export const LOCAL_SUPABASE_ENV_HEADER =
    '# Generated by write-local-supabase-env.ts for disposable local Supabase.';

export interface LocalSupabaseKeys {
    apiUrl: string;
    publishableKey: string;
    secretKey: string;
}

export interface LocalSupabaseSecrets {
    cronSecret: string;
    rateLimitSalt: string;
}

function firstQuoted(statusEnv: string, names: readonly string[]): string | undefined {
    for (const name of names) {
        const match = new RegExp(`^${name}="([^"]+)"`, 'm').exec(statusEnv);
        if (match?.[1]) return match[1];
    }
    return undefined;
}

export function parseSupabaseStatusEnv(statusEnv: string): LocalSupabaseKeys {
    const apiUrl = firstQuoted(statusEnv, ['API_URL']);
    const publishableKey = firstQuoted(statusEnv, ['PUBLISHABLE_KEY', 'ANON_KEY']);
    const secretKey = firstQuoted(statusEnv, ['SECRET_KEY', 'SERVICE_ROLE_KEY']);
    if (!apiUrl || !publishableKey || !secretKey) {
        throw new Error('supabase status did not include API_URL plus a publishable/anon key and a secret/service_role key.');
    }
    return { apiUrl, publishableKey, secretKey };
}

export function renderLocalSupabaseEnv(keys: LocalSupabaseKeys, secrets: LocalSupabaseSecrets): string {
    return [
        LOCAL_SUPABASE_ENV_HEADER,
        '# Browser values are public. The secret key must never use a VITE_ prefix.',
        `VITE_SUPABASE_URL=${keys.apiUrl}`,
        `VITE_SUPABASE_PUBLISHABLE_KEY=${keys.publishableKey}`,
        `SUPABASE_URL=${keys.apiUrl}`,
        `SUPABASE_PUBLISHABLE_KEY=${keys.publishableKey}`,
        `SUPABASE_SECRET_KEY=${keys.secretKey}`,
        `RATE_LIMIT_SALT=${secrets.rateLimitSalt}`,
        `CRON_SECRET=${secrets.cronSecret}`,
        '',
    ].join('\n');
}

export function assertCanWriteLocalEnv(existing: string | null, force: boolean): void {
    if (force || existing === null) return;
    if (existing.startsWith(LOCAL_SUPABASE_ENV_HEADER)) return;
    throw new Error('Refusing to overwrite .env.local that was not generated for disposable local Supabase. Re-run with --force if you intend to replace it.');
}
